/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.Entity.ClienteVip;

/**
 *
 * @author User
 */
public class ClienteVipVista extends javax.swing.JFrame {
    private String cedula;
    /**
     * Creates new form ClienteVip
     * @param cedula
     */
    public ClienteVipVista(String cedula) {
        initComponents();
        this.cedula = cedula;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_guardarDatosCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_eliminarDatosCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMembresiaVip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAsesorVip = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCreditoVip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescuentoVip = new javax.swing.JTextField();
        btn_guardarDatosCliente1 = new javax.swing.JButton();
        btn_eliminarDatosCliente1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        btn_guardarDatosCliente.setBackground(new java.awt.Color(176, 206, 255));
        btn_guardarDatosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save-as_37111.png"))); // NOI18N
        btn_guardarDatosCliente.setText("GUARDAR");
        btn_guardarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDatosClienteActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        btn_eliminarDatosCliente.setBackground(new java.awt.Color(255, 102, 102));
        btn_eliminarDatosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/action_exit_close_remove_13915.png"))); // NOI18N
        btn_eliminarDatosCliente.setText("ELIMINAR");
        btn_eliminarDatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarDatosClienteActionPerformed(evt);
            }
        });

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 151, 178));
        jLabel2.setText("12.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 109, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Numero de Membresía:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 19, -1, -1));

        txtMembresiaVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMembresiaVipActionPerformed(evt);
            }
        });
        jPanel1.add(txtMembresiaVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 47, 165, 31));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 151, 178));
        jLabel4.setText("10.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel5.setText("Asesor Asignado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 106, -1, -1));

        txtAsesorVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsesorVipActionPerformed(evt);
            }
        });
        jPanel1.add(txtAsesorVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 140, 155, 31));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 151, 178));
        jLabel6.setText("11-");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 22, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel7.setText("Cantidad De Credito:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 19, -1, -1));

        txtCreditoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditoVipActionPerformed(evt);
            }
        });
        jPanel1.add(txtCreditoVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 47, 165, 31));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 151, 178));
        jLabel8.setText("13.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 109, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setText("Descuento;");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 106, -1, -1));

        txtDescuentoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoVipActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuentoVip, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 140, 165, 31));

        btn_guardarDatosCliente1.setBackground(new java.awt.Color(176, 206, 255));
        btn_guardarDatosCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save-as_37111.png"))); // NOI18N
        btn_guardarDatosCliente1.setText("GUARDAR");
        btn_guardarDatosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDatosCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardarDatosCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 225, -1, -1));

        btn_eliminarDatosCliente1.setBackground(new java.awt.Color(255, 102, 102));
        btn_eliminarDatosCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/action_exit_close_remove_13915.png"))); // NOI18N
        btn_eliminarDatosCliente1.setText("ELIMINAR");
        btn_eliminarDatosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarDatosCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminarDatosCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 225, -1, -1));

        jButton2.setText("volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 225, 99, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 280));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDatosClienteActionPerformed


    }//GEN-LAST:event_btn_guardarDatosClienteActionPerformed

    private void btn_eliminarDatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarDatosClienteActionPerformed


    }//GEN-LAST:event_btn_eliminarDatosClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_eliminarDatosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarDatosCliente1ActionPerformed
        txtMembresiaVip.setText("");
        txtCreditoVip.setText("");
        txtDescuentoVip.setText("");
        txtAsesorVip.setText("");
    }//GEN-LAST:event_btn_eliminarDatosCliente1ActionPerformed

    private void btn_guardarDatosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDatosCliente1ActionPerformed
        String membresia = txtMembresiaVip.getText();
        String credito = txtCreditoVip.getText();
        String asesor = txtAsesorVip.getText();
        String descuento = txtDescuentoVip.getText();
        int membresia2 = Integer.parseInt(membresia);
        double credito2 = Double.parseDouble(credito);
        double descuento2 = Double.parseDouble(descuento);
        
        
        ClienteVip vip = new ClienteVip(asesor, credito2,membresia2 , descuento2, cedula);
        
        
        
        
        
    }//GEN-LAST:event_btn_guardarDatosCliente1ActionPerformed

    private void txtDescuentoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoVipActionPerformed

    private void txtCreditoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditoVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditoVipActionPerformed

    private void txtAsesorVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsesorVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsesorVipActionPerformed

    private void txtMembresiaVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMembresiaVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMembresiaVipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminarDatosCliente;
    private javax.swing.JButton btn_eliminarDatosCliente1;
    private javax.swing.JButton btn_guardarDatosCliente;
    private javax.swing.JButton btn_guardarDatosCliente1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAsesorVip;
    private javax.swing.JTextField txtCreditoVip;
    private javax.swing.JTextField txtDescuentoVip;
    private javax.swing.JTextField txtMembresiaVip;
    // End of variables declaration//GEN-END:variables
}
