/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.Entity.ClienteFrecuente;

/**
 *
 * @author User
 */
public class ClienteFrecuenteVistas extends javax.swing.JFrame {
    private String cedula;
    /**
     * Creates new form ClienteFrecuente
     * @param cedula
     */

    public ClienteFrecuenteVistas(String cedula) {
        initComponents();
        this.cedula = cedula;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMembresiaF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescuentoF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_eliminarDatosCliente1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_guardarDatosCliente1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel3.setText("Numero de Membresía:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 19, -1, -1));

        txtMembresiaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMembresiaFActionPerformed(evt);
            }
        });
        jPanel1.add(txtMembresiaF, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 47, 165, 31));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 151, 178));
        jLabel4.setText("10.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, -1, -1));

        txtDescuentoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoFActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuentoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 47, 165, 31));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 151, 178));
        jLabel8.setText("11.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 22, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel9.setText("Descuento;");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 19, -1, -1));

        btn_eliminarDatosCliente1.setBackground(new java.awt.Color(255, 102, 102));
        btn_eliminarDatosCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/action_exit_close_remove_13915.png"))); // NOI18N
        btn_eliminarDatosCliente1.setText("ELIMINAR");
        btn_eliminarDatosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarDatosCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminarDatosCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jButton2.setText("volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 99, 39));

        btn_guardarDatosCliente1.setBackground(new java.awt.Color(176, 206, 255));
        btn_guardarDatosCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Save-as_37111.png"))); // NOI18N
        btn_guardarDatosCliente1.setText("GUARDAR");
        btn_guardarDatosCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDatosCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardarDatosCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 290));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMembresiaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMembresiaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMembresiaFActionPerformed

    private void txtDescuentoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoFActionPerformed

    private void btn_guardarDatosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDatosCliente1ActionPerformed
        String membresia = txtMembresiaF.getText();
        String descuento = txtDescuentoF.getText();

        int membresia2 = Integer.parseInt(membresia);
        double descuento2 = Double.parseDouble(descuento);

        ClienteFrecuente frecuente = new ClienteFrecuente(membresia2, descuento2, cedula);

    }//GEN-LAST:event_btn_guardarDatosCliente1ActionPerformed

    private void btn_eliminarDatosCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarDatosCliente1ActionPerformed
        txtMembresiaF.setText("");
        txtDescuentoF.setText("");
    }//GEN-LAST:event_btn_eliminarDatosCliente1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminarDatosCliente1;
    private javax.swing.JButton btn_guardarDatosCliente1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescuentoF;
    private javax.swing.JTextField txtMembresiaF;
    // End of variables declaration//GEN-END:variables
}
